version: '3.5'

services:
  postgresql:
    image: 'bitnami/postgresql:latest'
    container_name: 'postgresql'
    hostname: postgresql
    environment:
      - POSTGRESQL_PASSWORD=notes-app-PASS
      - POSTGRESQL_USERNAME=notes-app
    networks:
      - notes-app
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U notes-app"]
      interval: 10s
      timeout: 5s
      retries: 10


  identity-server:
    image: 'mnormatov2001/notes-identity-server-dev:latest'
    container_name: 'auth'
    hostname: auth.notes.com
    restart: unless-stopped
    depends_on: 
      postgresql:
        condition: service_healthy
    ports:
      - '7291:7291'
    networks:
      - notes-app

  notes-api:
    image: 'mnormatov2001/notes-api-dev:latest'
    container_name: 'api'
    hostname: api.notes.com
    restart: unless-stopped
    depends_on: 
      postgresql:
        condition: service_healthy
    ports:
      - '7090:7090'
    networks:
      - notes-app

volumes:
  postgresql_data:

networks:
  notes-app:
    driver: bridge
